// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwpANsN5oGr6sFq-W7-WoricUkkItcY3Y',
    appId: '1:237587258513:web:f327d2759db37712d83330',
    messagingSenderId: '237587258513',
    projectId: 'spotify-8c520',
    authDomain: 'spotify-8c520.firebaseapp.com',
    storageBucket: 'spotify-8c520.firebasestorage.app',
    measurementId: 'G-4QMG4D8BK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBasu7ejfiFxa38WazB_d6wA4pMu-yukmw',
    appId: '1:237587258513:android:a51a2254ec685b35d83330',
    messagingSenderId: '237587258513',
    projectId: 'spotify-8c520',
    storageBucket: 'spotify-8c520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCetKGNNXjSwh9qdzS-TNEB00ql93h5wmI',
    appId: '1:237587258513:ios:5268e588b36294a4d83330',
    messagingSenderId: '237587258513',
    projectId: 'spotify-8c520',
    storageBucket: 'spotify-8c520.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCetKGNNXjSwh9qdzS-TNEB00ql93h5wmI',
    appId: '1:237587258513:ios:5268e588b36294a4d83330',
    messagingSenderId: '237587258513',
    projectId: 'spotify-8c520',
    storageBucket: 'spotify-8c520.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwpANsN5oGr6sFq-W7-WoricUkkItcY3Y',
    appId: '1:237587258513:web:123a9ae3e7a5ad57d83330',
    messagingSenderId: '237587258513',
    projectId: 'spotify-8c520',
    authDomain: 'spotify-8c520.firebaseapp.com',
    storageBucket: 'spotify-8c520.firebasestorage.app',
    measurementId: 'G-3SZJL271F8',
  );
}
